/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
<<<<<<< HEAD

=======
>>>>>>> 57548bb7f3dbae91d1afebfec33bd4b494d16e66
package de.cismet.projecttracker.report.db.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ActivityWorkPackage generated by hbm2java.
 *
 * @version  $Revision$, $Date$
 */
@Entity
@Table(
    name = "funding",
    schema = "public"
)
public class Funding extends BasicHibernateEntity {

    //~ Instance fields --------------------------------------------------------

    private Project project;
    private Company company;
    private double fundingratio;

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates a new Funding object.
     */
    public Funding() {
    }

    /**
     * Creates a new Funding object.
     *
     * @param  id            DOCUMENT ME!
     * @param  fundingratio  DOCUMENT ME!
     * @param  project       DOCUMENT ME!
     * @param  company       DOCUMENT ME!
     */
    public Funding(final long id, final double fundingratio, final Project project, final Company company) {
        this.id = id;
        this.project = project;
        this.fundingratio = fundingratio;
        this.company = company;
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    @Column(
        name = "fundingratio",
        nullable = false,
        precision = 6
    )
    public double getFundingratio() {
        return this.fundingratio;
    }

    /**
     * DOCUMENT ME!
     *
     * @param  workinghours  DOCUMENT ME!
     */
    public void setFundingratio(final double workinghours) {
        this.fundingratio = workinghours;
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
        name = "projectid",
        nullable = false
    )
    public Project getProject() {
        return this.project;
    }

    /**
     * DOCUMENT ME!
     *
     * @param  project  DOCUMENT ME!
     */
    public void setProject(final Project project) {
        this.project = project;
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "companyid")
    public Company getCompany() {
        return this.company;
    }

    /**
     * DOCUMENT ME!
     *
     * @param  company  DOCUMENT ME!
     */
    public void setCompany(final Company company) {
        this.company = company;
    }
}
