/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.projecttracker.report.db.entities;
// Generated Feb 12, 2010 1:07:58 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TravelDocument generated by hbm2java.
 *
 * @version  $Revision$, $Date$
 */
@Entity
@Table(
    name = "travel_document",
    schema = "public"
)
public class TravelDocument extends BasicHibernateEntity {

    //~ Instance fields --------------------------------------------------------

    private Travel travel;
    private String documentname;
    private String mimetype;
    private byte[] document;

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates a new TravelDocument object.
     */
    public TravelDocument() {
    }

    /**
     * Creates a new TravelDocument object.
     *
     * @param  id            DOCUMENT ME!
     * @param  travel        DOCUMENT ME!
     * @param  documentname  DOCUMENT ME!
     * @param  mimetype      DOCUMENT ME!
     * @param  document      DOCUMENT ME!
     */
    public TravelDocument(final long id,
            final Travel travel,
            final String documentname,
            final String mimetype,
            final byte[] document) {
        this.id = id;
        this.travel = travel;
        this.documentname = documentname;
        this.mimetype = mimetype;
        this.document = document;
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
        name = "travelid",
        nullable = false
    )
    public Travel getTravel() {
        return this.travel;
    }

<<<<<<< HEAD
    public void setTravel(Travel travel) {
        this.travel = travel;
    }

    @Column(name="documentname", nullable=false, length=50)
=======
    /**
     * DOCUMENT ME!
     *
     * @param  travel  DOCUMENT ME!
     */
    public void setTravel(final Travel travel) {
        this.travel = travel;
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    @Column(
        name = "documentname",
        nullable = false,
        length = 50
    )
>>>>>>> 57548bb7f3dbae91d1afebfec33bd4b494d16e66
    public String getDocumentname() {
        return this.documentname;
    }

<<<<<<< HEAD
    public void setDocumentname(String documentname) {
        this.documentname = documentname;
    }

    @Column(name="mimetype", nullable=false, length=100)
=======
    /**
     * DOCUMENT ME!
     *
     * @param  documentname  DOCUMENT ME!
     */
    public void setDocumentname(final String documentname) {
        this.documentname = documentname;
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    @Column(
        name = "mimetype",
        nullable = false,
        length = 100
    )
>>>>>>> 57548bb7f3dbae91d1afebfec33bd4b494d16e66
    public String getMimetype() {
        return this.mimetype;
    }

<<<<<<< HEAD
    public void setMimetype(String mimetype) {
        this.mimetype = mimetype;
    }

    @Column(name="document", nullable=false)
=======
    /**
     * DOCUMENT ME!
     *
     * @param  mimetype  DOCUMENT ME!
     */
    public void setMimetype(final String mimetype) {
        this.mimetype = mimetype;
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    @Column(
        name = "document",
        nullable = false
    )
>>>>>>> 57548bb7f3dbae91d1afebfec33bd4b494d16e66
    public byte[] getDocument() {
        return this.document;
    }

<<<<<<< HEAD
    public void setDocument(byte[] document) {
        this.document = document;
    }
}


=======
    /**
     * DOCUMENT ME!
     *
     * @param  document  DOCUMENT ME!
     */
    public void setDocument(final byte[] document) {
        this.document = document;
    }
}
>>>>>>> 57548bb7f3dbae91d1afebfec33bd4b494d16e66
