package de.cismet.projecttracker.report.db.entities;
// Generated Feb 12, 2010 1:07:58 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TravelDocument generated by hbm2java
 */
@Entity
@Table(name="travel_document"
    ,schema="public"
)
public class TravelDocument extends BasicHibernateEntity {
     private Travel travel;
     private String documentname;
     private String mimetype;
     private byte[] document;

    public TravelDocument() {
    }

    public TravelDocument(long id, Travel travel, String documentname, String mimetype, byte[] document) {
       this.id = id;
       this.travel = travel;
       this.documentname = documentname;
       this.mimetype = mimetype;
       this.document = document;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="travelid", nullable=false)
    public Travel getTravel() {
        return this.travel;
    }

    public void setTravel(Travel travel) {
        this.travel = travel;
    }

    @Column(name="documentname", nullable=false, length=50)
    public String getDocumentname() {
        return this.documentname;
    }

    public void setDocumentname(String documentname) {
        this.documentname = documentname;
    }

    @Column(name="mimetype", nullable=false, length=100)
    public String getMimetype() {
        return this.mimetype;
    }

    public void setMimetype(String mimetype) {
        this.mimetype = mimetype;
    }

    @Column(name="document", nullable=false)
    public byte[] getDocument() {
        return this.document;
    }

    public void setDocument(byte[] document) {
        this.document = document;
    }
}


