package de.cismet.projecttracker.report.db.entities;
// Generated Feb 11, 2010 12:17:36 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Travel generated by hbm2java
 */
@Entity
@Table(name="travel"
    ,schema="public"
)
public class Travel extends BasicHibernateEntity {
     private Staff staff;
     private Project project;
     private double grossprice;
     private double netprice;
     private double allowablevat;
     private Date date;
     private String destination;
     private String description;
     private String storagelocation;
     private Date paymentdate;
     private Set<TravelDocument> traveldocuments = new HashSet<TravelDocument>(0);

    public Travel() {
    }

	
    public Travel(long id, Staff staff, double grossprice, double netprice, Date date, String destination) {
        this.id = id;
        this.staff = staff;
        this.grossprice = grossprice;
        this.netprice = netprice;
        this.date = date;
        this.destination = destination;
    }


    public Travel(long id, Staff staff, double grossprice, double netprice, double allowablevat, Date date, String destination, String description, String storagelocation, Date paymentdate, Set<TravelDocument> traveldocuments, Project project) {
       this.id = id;
       this.staff = staff;
       this.grossprice = grossprice;
       this.netprice = netprice;
       this.allowablevat = allowablevat;
       this.date = date;
       this.destination = destination;
       this.description = description;
       this.storagelocation = storagelocation;
       this.paymentdate = paymentdate;
       this.traveldocuments = traveldocuments;
       this.project = project;
    }
   
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="staffid", nullable=false)
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="projectid", nullable=false)
    public Project getProject() {
        return this.project;
    }

    public void setProject(Project project) {
        this.project = project;
    }

    @Column(name="grossprice", nullable=false, precision=10)
    public double getGrossprice() {
        return this.grossprice;
    }
    
    public void setGrossprice(double grossprice) {
        this.grossprice = grossprice;
    }
    
    @Column(name="netprice", nullable=false, precision=10)
    public double getNetprice() {
        return this.netprice;
    }
    
    public void setNetprice(double netprice) {
        this.netprice = netprice;
    }
    
    @Column(name="allowablevat", precision=10)
    public double getAllowablevat() {
        return this.allowablevat;
    }
    
    public void setAllowablevat(double allowablevat) {
        this.allowablevat = allowablevat;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=29)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    
    @Column(name="destination", nullable=false, length=50)
    public String getDestination() {
        return this.destination;
    }
    
    public void setDestination(String destination) {
        this.destination = destination;
    }
    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="storagelocation", length=100)
    public String getStoragelocation() {
        return this.storagelocation;
    }
    
    public void setStoragelocation(String storagelocation) {
        this.storagelocation = storagelocation;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="paymentdate", length=29)
    public Date getPaymentdate() {
        return this.paymentdate;
    }
    
    public void setPaymentdate(Date paymentdate) {
        this.paymentdate = paymentdate;
    }

    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="travel")
    public Set<TravelDocument> getTraveldocuments() {
        return this.traveldocuments;
    }
    
    public void setTraveldocuments(Set<TravelDocument> traveldocuments) {
        this.traveldocuments = traveldocuments;
    }
}


