package de.cismet.projecttracker.report.db.entities;
// Generated Mar 1, 2010 11:21:54 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Warning generated by hbm2java
 */
@Entity
@Table(name="warning"
    ,schema="public"
)
public class Warning extends BasicHibernateEntity {
     private WorkPackage workPackage;
     private int level;
     private Date time;

    public Warning() {
    }

	
    public Warning(long id, int level, Date time) {
        this.id = id;
        this.level = level;
        this.time = time;
    }

    public Warning(long id, WorkPackage workPackage, int level, Date time) {
       this.id = id;
       this.workPackage = workPackage;
       this.level = level;
       this.time = time;
    }
   
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="projectcomponentid")
    public WorkPackage getWorkPackage() {
        return this.workPackage;
    }
    
    public void setWorkPackage(WorkPackage workPackage) {
        this.workPackage = workPackage;
    }
    
    @Column(name="level", nullable=false)
    public int getLevel() {
        return this.level;
    }
    
    public void setLevel(int level) {
        this.level = level;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="time", nullable=false, length=29)
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }




}


