/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.projecttracker.report.db.entities;
// Generated Mar 1, 2010 11:21:54 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Warning generated by hbm2java.
 *
 * @version  $Revision$, $Date$
 */
@Entity
@Table(
    name = "warning",
    schema = "public"
)
public class Warning extends BasicHibernateEntity {

    //~ Instance fields --------------------------------------------------------

    private WorkPackage workPackage;
    private int level;
    private Date time;

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates a new Warning object.
     */
    public Warning() {
    }

    /**
     * Creates a new Warning object.
     *
     * @param  id     DOCUMENT ME!
     * @param  level  DOCUMENT ME!
     * @param  time   DOCUMENT ME!
     */
    public Warning(final long id, final int level, final Date time) {
        this.id = id;
        this.level = level;
        this.time = time;
    }

    /**
     * Creates a new Warning object.
     *
     * @param  id           DOCUMENT ME!
     * @param  workPackage  DOCUMENT ME!
     * @param  level        DOCUMENT ME!
     * @param  time         DOCUMENT ME!
     */
    public Warning(final long id, final WorkPackage workPackage, final int level, final Date time) {
        this.id = id;
        this.workPackage = workPackage;
        this.level = level;
        this.time = time;
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "projectcomponentid")
    public WorkPackage getWorkPackage() {
        return this.workPackage;
    }

    /**
     * DOCUMENT ME!
     *
     * @param  workPackage  DOCUMENT ME!
     */
    public void setWorkPackage(final WorkPackage workPackage) {
        this.workPackage = workPackage;
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    @Column(
        name = "level",
        nullable = false
    )
    public int getLevel() {
        return this.level;
    }

    /**
     * DOCUMENT ME!
     *
     * @param  level  DOCUMENT ME!
     */
    public void setLevel(final int level) {
        this.level = level;
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(
        name = "time",
        nullable = false,
        length = 29
    )
    public Date getTime() {
        return this.time;
    }

    /**
     * DOCUMENT ME!
     *
     * @param  time  DOCUMENT ME!
     */
    public void setTime(final Date time) {
        this.time = time;
    }
}
