/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.projecttracker.report.db.entities;
// Generated Feb 5, 2010 11:22:10 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkPackageProgress generated by hbm2java.
 *
 * @version  $Revision$, $Date$
 */
@Entity
@Table(
    name = "work_package_progress",
    schema = "public"
)
public class WorkPackageProgress extends BasicHibernateEntity {

    //~ Instance fields --------------------------------------------------------

    private WorkPackage workPackage;
    private Date time;
    private int progress;

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates a new WorkPackageProgress object.
     */
    public WorkPackageProgress() {
    }

    /**
     * Creates a new WorkPackageProgress object.
     *
     * @param  id           DOCUMENT ME!
     * @param  workPackage  DOCUMENT ME!
     * @param  time         DOCUMENT ME!
     * @param  progress     DOCUMENT ME!
     */
    public WorkPackageProgress(final long id, final WorkPackage workPackage, final Date time, final int progress) {
        this.id = id;
        this.workPackage = workPackage;
        this.time = time;
        this.progress = progress;
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
        name = "id",
        unique = true,
        nullable = false,
        insertable = false,
        updatable = false
    )
    public WorkPackage getWorkPackage() {
        return this.workPackage;
    }

    /**
     * DOCUMENT ME!
     *
     * @param  workPackage  DOCUMENT ME!
     */
    public void setWorkPackage(final WorkPackage workPackage) {
        this.workPackage = workPackage;
    }
    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(
        name = "time",
        nullable = false,
        length = 29
    )
    public Date getTime() {
        return this.time;
    }

    /**
     * DOCUMENT ME!
     *
     * @param  time  DOCUMENT ME!
     */
    public void setTime(final Date time) {
        this.time = time;
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    @Column(
        name = "progress",
        nullable = false
    )
    public int getProgress() {
        return this.progress;
    }

    /**
     * DOCUMENT ME!
     *
     * @param  progress  DOCUMENT ME!
     */
    public void setProgress(final int progress) {
        this.progress = progress;
    }
}
